server:
  port: 9106
dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.1.77:2181
  metadata-report:
    address: zookeeper://192.168.1.77:2181
  consumer:
    check: false



