server:
  port: 9107

dubbo:
  scan:
    base-packages: com.jekken.dubbo.service.impl
  application:
    name: dubbo-privider
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.1.77:2181
  metadata-report:
    address: zookeeper://192.168.1.77:2181
  consumer:
    check: false
